name: Docker Image build and push 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Commit ID
      run: |
        COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-5)
        echo "commit id is $COMMIT_ID"
    # - name: commit id egenarator 
    #   run: |
    #     COMMIT-ID=$(git rev-parse --short=6 HEAD)
    #     echo "commit id is $COMMIT-ID"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: |
          docker build -t docker.io/razoropsrepocode/amazon:${COMMIT_ID} 
          #          \    --build-arg COMMIT_ID=${COMMIT_ID} \
    
      
    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #       push: true
    #       tags: razoropsrepocode/amazon:$COMMIT-ID
  
    # - name: commit id egenarator 
    #   run: |
    #     COMMIT-ID=$(git rev-parse --short=6 HEAD)
    #     echo "commit id is $COMMIT-ID"
       
        
#     # - name: Login to Docker Hub
#     #   run: |
#     #     docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

         
#     # - name: Push Docker image
#     #   run: |
#     #      # COMMIT-ID=$(git rev-parse --short=6 HEAD)
#     #       # IMAGE_TAG="razoropsrepocode/amazon:V-${COMMIT-ID}"
#     #       # docker push "$IMAGE_TAG"
#     #       docker push razoropsrepocode/amazon:V-$COMMIT-ID

#     # - name: Run Trivy vulnerability scanner
#     #   run: COMMIT-ID=$(git rev-parse --short=6 HEAD)
#     #    echo "cpmmit id is $COMMIT-ID"
#     # - name: trivyscan 
#     #   uses: aquasecurity/trivy-action@master 
#     #   with:
#     #       image-ref: "docker.io/razoropsrepocode/amazon:V-$COMMIT-ID"
#     #       format: 'table'
#     #       exit-code: '1'
#     #       ignore-unfixed: true
#     #       vuln-type: 'os,library'
#     #       severity: 'CRITICAL,HIGH'
 
    
