name: Docker Image build and push 

env:
  COMMIT-ID: hi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    # echo  "::commitd is $(git rev-parse --short=6 HEAD) >> ${CIMMIT_ID}" 

    steps:
    - name: set COMMIT_ID for ENV
      run: echo "COMMIT-ID=$(git rev-parse --short=6 HEAD)" >> $GITHUB_ENV
        commit id is $COMMIT-ID
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        COMMIT-ID=$(git rev-parse --short=6 HEAD)
        echo "commit id is $COMMIT-ID"
        docker build -t razoropsrepocode/amazon:V-$COMMIT-ID . 
        
    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

         
    - name: Push Docker image
      run: |
         # COMMIT_ID=$(git rev-parse --short=6 HEAD)
          # IMAGE_TAG="razoropsrepocode/amazon:V-${COMMIT-ID}"
          # docker push "$IMAGE_TAG"
          docker push razoropsrepocode/amazon:V-$COMMIT-ID

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
    - name: Login to Docker Hub
        COMMIT-ID=$(git rev-parse --short=6 HEAD)
      with:
          image-ref: 'docker.io/razoropsrepocode/amazon:V-$COMMIT-ID'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
 
    
